version: "3"

services:
    nodeos:
        image: sweatpotato/leap:3.1.2
        container_name: ${NODE_NAME}
        command: nodeos --data-dir=/data --config-dir=/etc/nodeos ${SUB_COMMAND}
        volumes:
            - ./nodeos-data-volume/nodeos-data/config:/etc/nodeos
            - ./nodeos-data-volume/nodeos-data/data:/data
            - ./nodeos-data-volume/nodeos-data/contracts:/contracts
        ports:
            - "9876:9876"
            - "8888:8888"
            - "8080:8080"
